### ISSUE TITLE
Scroll to contact section

### ISSUE THREAD

**Issue by isedwards** [myacorn/fip-static#6]
@kgaraffa - is it possible to restore the behaviour of [the original theme](https://themewagon.github.io/TopicListing/) so that when you click CONTACT from the home page it automatically scrolls down to the contact section of the landing page - and, if the user is on the landing page, when they click HOME it scrolls back to the top of the page? It may just be a case of adding anchors with the correct names if the jQuery script is still being loaded.

**Comment by kgaraffa** [comment]
all set, added back in!

**Comment by isedwards** [comment]
Thank you! Merged in the main site now
